### PR TITLE
Executive Update

### PR DESCRIPTION
**Pull request by alexarcher721**

### CODE REVIEW

**Comment by Adina77** [comment]
Unless we also have a main.py file, executive should not be composed entirely of methods. So the code after the function definitions calls the functions in the executive file. First the setup method and then the playGame method. It allows repeat of calling these methods (both setup and then playGame) if the user wants to play again. So at least some of the code (and probably all of it) needs to be outside of playGame. We could put it inside yet another method (like run()) and then have main.py call the run() method, kind of following how we structured our C++ code in 268. But I thought that was really unnecessary. We were being taught how to structure much more complex programs, and that's why it was broken up so much. I don't have a strong pref of how we break things up, and how the code is arranged, but currently we do need to have code outside of functions in the executive file.

**Comment by Adina77** [comment]
Also, I was thinking playGame would be restricted to the function of taking shots at ships, and keeping track of the results of that. So executive code calls the setup and playGame methods and also has some messages that are printed only one time per game. So I had executive start in a while loop (so game can repeat until user says to quit after playGame finishes running). The printMenu allows users to quite in the middle of the game, so that is different. It is okay to rearrange but again executive needs code outside of functions.

**Comment by Adina77** [comment]
The other issue is, printMenu is just something that gets called between turns, giving players the option to quit at any time, print instructions at any time, and other things that are repeatedly printed at the start of every single turn. But maybe it can have an input parameter, which says which player it is to print for? So playGame() calls printMenu() and passes in argument for player number, so the boards (current player and opponent) are printed correctly. The other alternative is adding a menu option to print the boards which may be practical in a real-life situation, because you don't want to print boards 'till a players swap positions (who is sitting in front of the computer). OR, to keep some of the code that is in this pull request, here's an idea: add a print menu option to "Hide boards." This sets up for the next player, who now sits in front of the computer, and gets a new set of board printouts.

**Comment by Adina77** [comment]
COMMENTS FOR BOARD

The fix for the waterGrid in 2D array ranges is actually how I had also written it! But someone changed the ranges. Now Alex returned what I had and it works again :-)
Please, if you make changes, test first to make sure it did not break the code.

**Comment by Adina77** [comment]
Also: We no longer have a Ship Class or Ship objects, so probably we no longer need self.shipObjects list and no longer need to collect coordinates for ship objects, since we are keeping track of individual ships simply via their unique number when they are being placed on the board. So these were features in the old code, for the old plan of how to keep track of ships. Maybe just comment out in case we do want to add a simple Ship object to keep track of its state.

**Comment by alexarcher721** [comment]
We could keep track of ship coordinates with the unique numbers they have in the array, but self.shipObjects as it works now keeps track of the coordinates of all ships and can't be edited out as it is necessary for the hit method to function properly. If we want to change this we can, but the method using self.shipObjects works perfectly fine right now.
________________________________

**Comment by Adina77** [comment]
I added in the hits and score methods from this pull exactly as is (did not yet carefully check). They are not interfering with any other code so it is safe to add so I simply copy-pasted them.

**Comment by Adina77** [comment]
I guess my push created conflicts with this pull request, but I didn't really want to pull it because I already added in the parts from it that would not cause problems. The parts I did not add are explained in the above comments, except one part: I did not add in the bool for checking createShip inputs since Mac already added in the purpose of that method in his contribution to setup method.

**Comment by Adina77** [comment]
If things are working, I have no objection. But the whole point of numbering ships was that we no longer need ship objects and collect their coordinates when they are placed on the board, because we can simply traverse the waterGrid and get all the info we need from it. So I was thinking of a hit method that traverses the 2D array to find if the shoot hit any target, and if so, which one, so we can keep track of ship status. Collecting coordinates and making ship objects was needed only if we mark every ship the same way. The new plan was meant to simplify things.

**Comment by alexarcher721** [comment]
Yeah, I probably should have used the fact that we numbered the ship locations to make it easier for myself, but it works the way we have it now so it's fine.
________________________________

**Pull request closed without merging**
